{% set name = "asdf-transform-schemas" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdf_transform_schemas-{{ version }}.tar.gz
  sha256: de7fdc3fee35fb957fc32957877a0e9d7dd4d2e851bd631a7259f11c2bd294ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
  run:
    - importlib-resources >=3
    - python >=3.8
    - asdf-standard >=1.0.1

test:
  imports:
    - asdf_transform_schemas
  commands:
    - pip check
  requires:
    - pip
    - asdf >=2.8.0
    - asdf-astropy
    - scipy
    - pytest

about:
  home: https://github.com/asdf-format/asdf-transform-schemas
  summary: ASDF schemas for transforms
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhunkeler
    - braingram
    - nden
    - eslavich
