{% set name = "asdf-transform-schemas" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdf_transform_schemas-{{ version }}.tar.gz
  sha256: 82cf4c782575734a895327f25ff583ce9499d7e2b836fe8880b2d7961c6b462b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools-scm
  run:
    - python >=3.9
    - asdf-standard >=1.1.0

test:
  imports:
    - asdf_transform_schemas
  commands:
    - pip check
  requires:
    - pip
    - asdf >=2.8.0
    - asdf-astropy
    - scipy
    - pytest

about:
  home: https://github.com/asdf-format/asdf-transform-schemas
  summary: ASDF schemas for transforms
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhunkeler
    - WilliamJamieson
    - braingram
